### PR TITLE
Add assertScreenshot method

### PR DESCRIPTION
**Pull request by jpratt2**
Glib,

Here are some methods that may help in asserting full-page screenshots. The idea is to make it simpler to detect any difference in a webpage using a full-page screenshot.

assertScreenshotFP
screenshotFP

### CODE REVIEW

**Comment by jpratt2** [comment]
perhaps a better name is "compareScreenshot", simply because another program like jUnit will do the actual assertion, and it looks funny to have 2 assert method names in a row.
assertTrue(compareScreenshot())

**Comment by glib-briia** [comment]
Hi John, haven't got much time lately to take a look at this PR. Will try to merge over the weekend

**Comment by glib-briia** [comment]
Hi @jpratt2 ,

Very appreciate your interest and contribution, however what you are suggesting is specific to your implementation of screenshots comparison. Wrapping  Shutterbug.shootPage into compareScreenshotFP restricts access to methods available in Snapshot class if one want to perform some operation on screenshot before comparison. I've added overloaded equals and equalsWithDiff which take image path as parameter https://github.com/assertthat/selenium-shutterbug/commit/cc21d20effd95e4c4ee251aa459e0768fa29569e

Lets leave the logic of where to store and how to name the images to the users.

**Comment by jpratt2** [comment]
ok

**Pull request closed without merging**
